library(dplyr)
library(magrittr)
library(haven)
#read aha file currently in use
aha_17 <- read_sas("/Volumes/George_Surgeon_Projects/standardized_medicare_data_using_R/input/archive/aha_hosp_05_17.sas7bdat")

#read aha file for new year
aha_18 <- read_sas("/Volumes/DMH_Shared/Resources/Provider/AHA_American_Hosp_Assoc_Survey/SAS_Data_Files/AHA2018/aha2018.sas7bdat")

#set year (should be the year processing)
current_year = 2018

#extract mapped variables, refer to variable map in data folder
aha_new <- aha_18 %>% 
  select(MCRNUM, 
         REG,
         MLOCZIP, 
         ID, 
         HOSPBD, 
         BSC,
         CBSATYPE, 
         MAPP18, 
         MAPP2, 
         MAPP3, 
         MAPP5, 
         MAPP12,
         MAPP13, 
         MAPP8,
         MAPP19,
         FTERN,
         ADJADC,
         IPDTOT,
         MSICHOS,
         MSICSYS,
         SERV,
         MCDIPD,
         CNTRL,
         ADTCHOS, 
         ADTCSYS, 
         ADTCVEN,
         OTBONHOS, 
         HARTHOS, 
         KDNYHOS, 
         LIVRHOS, 
         LUNGHOS, 
         TISUHOS, 
         OTOTHHOS,
         OTBONSYS,
         OTBONVEN,
         HARTSYS, 	
         HARTVEN,	
         KDNYSYS, 	
         KDNYVEN,	
         LIVRSYS, 	
         LIVRVEN,	
         LUNGSYS, 	
         LUNGVEN,	
         TISUSYS, 	
         TISUVEN,	
         OTOTHSYS, 
         OTOTHVEN,
         TRAUML90) %>%
  mutate(PRVNUMGRP = MCRNUM,
         zip = MLOCZIP,
         prov_npi = NA,
         year = current_year,
         AHAID = ID,
         provteach = ifelse(MAPP8 == 1,1,0),
         provteach_all = ifelse((MAPP3 == 1 | MAPP5 == 1 | MAPP12 == 1 | MAPP13 == 1 | MAPP8== 1),1,0),
         provteach_minor = ifelse((MAPP3 == 1 | MAPP5 == 1 | MAPP12 == 1 | MAPP13 == 1),1,0),
         rntopt = ifelse(ADJADC>0,(FTERN/ADJADC),NA),
         RN_BED_ratio = ifelse(HOSPBD>0,round((FTERN/HOSPBD),.01),NA),
         nurse_ratio2 = ifelse(IPDTOT>0,(FTERN/IPDTOT*1000),NA),
         nurse_ratio = ifelse(IPDTOT>0,round((FTERN/IPDTOT),0.01),NA),
         bedsize_cat = ifelse(HOSPBD >= 500, 4, 
                              (ifelse(HOSPBD < 200, 1,
                                      (ifelse((200 <= HOSPBD && HOSPBD <= 349),2,3))))),
         bedsize_cat2 = ifelse(HOSPBD >= 500, 3, 
                               ifelse(HOSPBD < 250,1,2)),
         beds_lt200 = ifelse((HOSPBD < 200),1,0),
         beds_200_349 = ifelse((200 <= HOSPBD && HOSPBD <= 349),1,0),
         beds_350_499 = ifelse((350 <= HOSPBD && HOSPBD <= 499),1,0),
         beds_ge500 = ifelse((HOSPBD > 500),1,0),
         beds_lt250 = ifelse((HOSPBD < 250),1,0),
         beds_250_499 = ifelse((250 <= HOSPBD && HOSPBD <= 499),1,0),
         region_ne = ifelse((REG==1 | REG==2),1,0),
         region_west = ifelse((REG==8 | REG==9),1,0),
         region_midwest = ifelse((REG==4 | REG==6),1,0),
         region_south = ifelse((REG==3 | REG==5 | REG==7 | REG==0),1,0),
         region_cat = ifelse((REG==1 | REG==2),"North-East",
                             ifelse((REG==8 | REG==9),"West",
                                    ifelse((REG==4 | REG==6),"Mid-west",
                                           ifelse((REG==3 | REG==5 | REG==7 | REG==0),"South", NA)))),
         urban = ifelse(MAPP19 == 1,0,1),
         cbsa_rural = ifelse(CBSATYPE == "Rural",1,0),
         cbsa_urban = ifelse(CBSATYPE != "Rural",1,0),
         CriticalAH = ifelse(MAPP18 == 1,1,0),
         NCI_hosp = ifelse((SERV == 41 | MAPP2 == 1),1,0),
         mcdipdtoipdtot = ifelse(IPDTOT>0,round((MCDIPD/IPDTOT),0.01),NA),
         profit = ifelse((CNTRL == 30 | CNTRL == 31 | CNTRL == 32 | CNTRL == 33 ),1,
                         ifelse((CNTRL == 21 | CNTRL == 22 | CNTRL == 23),2,3)),
         for_profit = ifelse(profit == 1,1,0),
         non_profit = ifelse(profit == 2,1,0),
         other_profit = ifelse(profit == 3,1,0),
         tech_hosp = ifelse((ADTCHOS == 1 | ADTCSYS == 1 | ADTCVEN == 1),1,0),
         Transplant_serv = ifelse((OTBONHOS == 1 |  HARTHOS == 1 |  KDNYHOS == 1 |  LIVRHOS == 1 |  LUNGHOS == 1 |  
                                     TISUHOS == 1 | OTOTHHOS == 1 | OTBONSYS == 1 | OTBONVEN == 1 | HARTSYS == 1 | 
                                     HARTVEN == 1 | KDNYSYS == 1 | KDNYVEN == 1 | LIVRSYS == 1 | LIVRVEN == 1 | LUNGSYS == 1 |
                                     LUNGVEN == 1 |TISUSYS == 1 | TISUVEN == 1 | OTOTHSYS == 1 | OTOTHVEN == 1),1,0),
         Transplant_hosp = ifelse((OTBONHOS == 1 | HARTHOS == 1 | KDNYHOS == 1 |
                                   LIVRHOS == 1 | LUNGHOS == 1 | TISUHOS == 1 | OTOTHHOS == 1),1,0),
         Tech_Cardiac_Transplant = ifelse((tech_hosp == 1 | Transplant_hosp == 1),1,0),
         MedSurg_HospICU = ifelse(MSICHOS == 1,1,0),
         MedSurg_HlthsysICU = ifelse(MSICSYS == 1,1,0),
         MedSurg_NWICU = NA,
         TRAUML90_cat = ifelse(TRAUML90== 1,1,
                               ifelse(TRAUML90 == 2,2,
                                      ifelse(TRAUML90 == 3,3,
                                             ifelse(TRAUML90 == 4,4,NA)))),
         trauma_level1 = ifelse(TRAUML90== 1,1,0),
         trauma_level2 = ifelse(TRAUML90 == 2,1,0),
         trauma_level3 = ifelse(TRAUML90 == 3,1,0),
         trauma_level45 = ifelse(TRAUML90 == 4,1,0)) %>%
  select(PRVNUMGRP,
         zip,
         prov_npi,
         year,
         AHAID,
         provteach,
         provteach_all,
         provteach_minor,
         rntopt,
         RN_BED_ratio,
         nurse_ratio2,
         nurse_ratio,
         bedsize_cat,
         beds_lt200,
         beds_200_349,
         beds_350_499,
         beds_ge500,
         bedsize_cat2,
         beds_lt250,
         beds_250_499,
         region_ne,
         region_west,
         region_midwest,
         region_south,
         region_cat,
         urban,
         cbsa_rural,
         cbsa_urban,
         CriticalAH,
         NCI_hosp,
         mcdipdtoipdtot,
         profit,
         for_profit,
         non_profit,
         other_profit,
         tech_hosp,
         Transplant_serv,
         Transplant_hosp,
         Tech_Cardiac_Transplant,
         MedSurg_HospICU,
         MedSurg_HlthsysICU,
         MedSurg_NWICU,
         TRAUML90_cat,
         trauma_level1,
         trauma_level2,
         trauma_level3,
         trauma_level45)

#merge with old file to create updated file
aha_hosp_05_18 <- rbind(aha_17,aha_new) 

write.csv(aha_hosp_05_18,"/Volumes/George_Surgeon_Projects/standardized_medicare_data_using_R/input/aha_hosp_05_18.csv")
